name: t0703 # 프로젝트 이름이 't0703'임을 확인합니다.
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  go_router: ^14.1.4
  provider: ^6.1.2
  http: ^1.2.1
  image_picker: ^1.1.2
  path_provider: ^2.1.3
  intl: ^0.19.0 # ✅ intl 패키지 확인
  camera: ^0.10.5+9
  table_calendar: ^3.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/ # ❗❗ 중요: 이 경로(t0703/assets/images/)가 프로젝트 폴더 내에 실제로 존재하는지 확인해주세요.
                      # 만약 없다면, t0703 폴더 안에 'assets' 폴더를 만들고, 그 안에 'images' 폴더를 만들어야 합니다.
                      # 그리고 'image_3991dd.jpg'와 같은 이미지 파일들을 그 'images' 폴더 안에 넣어주세요.
